### ISSUE TITLE
Rails server won't start when using gem

### ISSUE THREAD

**Issue by watson** [wavii/rails-dev-tweaks#3] opened 2011-09-19 19:20 UTC
After adding `gem 'rails-dev-tweaks', '0.5.0'` to the development group in the Gemfile, I get the following error and stacktrace when starting the Rails server

```
NoMethodError (undefined method `call' for nil:NilClass):

activesupport (3.1.0) lib/active_support/whiny_nil.rb:48:in `method_missing'
routing-filter (0.2.4) lib/routing_filter/adapters/rails_3.rb:74:in `recognize_with_filtering'
rails-dev-tweaks (0.5.0) lib/rails_dev_tweaks/granular_autoload/matchers/asset_matcher.rb:4:in `call'
rails-dev-tweaks (0.5.0) lib/rails_dev_tweaks/configuration.rb:72:in `block in should_reload?'
rails-dev-tweaks (0.5.0) lib/rails_dev_tweaks/configuration.rb:71:in `each'
rails-dev-tweaks (0.5.0) lib/rails_dev_tweaks/configuration.rb:71:in `should_reload?'
rails-dev-tweaks (0.5.0) lib/rails_dev_tweaks/granular_autoload/middleware.rb:21:in `call'
rack (1.3.2) lib/rack/sendfile.rb:101:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
railties (3.1.0) lib/rails/rack/logger.rb:13:in `call'
rack (1.3.2) lib/rack/methodoverride.rb:24:in `call'
rack (1.3.2) lib/rack/runtime.rb:17:in `call'
activesupport (3.1.0) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.3.2) lib/rack/lock.rb:15:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/static.rb:53:in `call'
dragonfly (0.9.5) lib/dragonfly/cookie_monster.rb:9:in `call'
dragonfly (0.9.5) lib/dragonfly/middleware.rb:13:in `call'
rack-cache (1.0.3) lib/rack/cache/context.rb:132:in `forward'
rack-cache (1.0.3) lib/rack/cache/context.rb:243:in `fetch'
rack-cache (1.0.3) lib/rack/cache/context.rb:181:in `lookup'
rack-cache (1.0.3) lib/rack/cache/context.rb:65:in `call!'
rack-cache (1.0.3) lib/rack/cache/context.rb:50:in `call'
railties (3.1.0) lib/rails/engine.rb:455:in `call'
railties (3.1.0) lib/rails/railtie/configurable.rb:30:in `method_missing'
rack (1.3.2) lib/rack/urlmap.rb:52:in `block in call'
rack (1.3.2) lib/rack/urlmap.rb:46:in `each'
rack (1.3.2) lib/rack/urlmap.rb:46:in `call'
rack (1.3.2) lib/rack/showexceptions.rb:24:in `call'
railties (3.1.0) lib/rails/rack/content_length.rb:16:in `call'
railties (3.1.0) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.3.2) lib/rack/handler/webrick.rb:59:in `service'
/Users/watson/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/Users/watson/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/Users/watson/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

**Comment by nevir** [comment] 2011-09-20 18:45
Hmm, could you post your Gemfile as well?  Looks like `rails-dev-tweaks` might be interacting poorly with one of your other dependencies (probably `routing-filter`, but it'll be helpful to get the full set to verify)

**Comment by nevir** [comment] 2011-09-20 19:01
Aha, it does look like it's `routing-filter`.  Try the latest version of it, which includes a patch for this issue:

```
gem 'routing-filter', :git => "https://github.com/svenfuchs/routing-filter"
```

**Comment by ugisozols** [comment] 2011-09-29 04:27
We're using routing-filter too and were facing the same error. Using your fork it works like a charm. Thanks!

**Comment by nevir** [comment] 2011-09-29 05:13
Awesome!  I'll send that up stream then :)

**Comment by nevir** [comment] 2011-09-29 05:17
https://github.com/svenfuchs/routing-filter/pull/29

**Comment by watson** [comment] 2011-09-29 09:00
Sorry for not getting back on this issue sooner. It works for me too :) Great work

**Comment by dvandersluis** [comment] 2011-12-07 01:11
Thanks for this, worked perfectly! :)

**Comment by dvandersluis** [comment] 2011-12-12 19:48
Actually there is a problem; with routing-filter and rails-dev-tweaks both enabled, and using `filter :locale` in routes.rb, the locale param is lost (ie. if params is dumped out it won't contain a locale key). `params[:locale]` is properly set if rails-dev-tweaks is disabled.

**Comment by dvandersluis** [comment] 2011-12-12 23:54
From what I can tell, the problem I mentioned above is caused by `recognize` being called on the routeset as part of matching an asset. My fix just duplicates the route set so that when `@app.call` is called in middleware.rb, the params are retained.

**Comment by nevir** [comment] 2011-12-21 19:44
My patch [was merged](https://github.com/svenfuchs/routing-filter/commit/99748040e43b806b99b7dcb7c45fd3b69e7edc46) into [routing-filter](https://github.com/svenfuchs/routing-filter).  

I'm killing off my fork, but keeping this issue open until there's a gem release of routing filter w/ it included

**Comment by nevir** [comment] 2012-01-17 02:27
routing-filter v0.3.0 fixes this, closing.

**Closed as completed by nevir** 2012-01-17 02:27 UTC
Labels: Pending Upstream
